sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shashankshroti27/docker-react -f Dockerfile.dev .

script:
  - docker run shashankshroti27/docker-react npm run test -- -- coverage
